channels: ['275242320339927040']
posts: 3
message: "What should I be made to say?"
hentai_haven: {
  enabled: True,
  posts: 0,
  channels: [],
  embed_colour: FF0000,
  blacklist: [
  ],
}
hanime_tv: {
  enabled: True,
  posts: 0,
  channels: [],
  embed_colour: FF00FF,
  section: "Recent Uploads"
}
reddit: {
  hentai_irl: {
    posts: ,
    channels: ['378437336712609792'],
  },
}
